import { Guest } from '@/types/hotel';
import { v4 as uuidv4 } from 'uuid';

export const mockGuests: Guest[] = [
  {
    id: uuidv4(),
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@example.com',
    phone: '+1234567890',
    documentType: 'Passport',
    documentNumber: 'AB123456',
  },
  {
    id: uuidv4(),
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'jane.smith@example.com',
    phone: '+1987654321',
    documentType: 'ID Card',
    documentNumber: 'XY789012',
  },
  {
    id: uuidv4(),
    firstName: 'Michael',
    lastName: 'Johnson',
    email: 'michael.johnson@example.com',
    phone: '+1122334455',
    documentType: 'Driver License',
    documentNumber: 'DL345678',
  },
  {
    id: uuidv4(),
    firstName: 'Emily',
    lastName: 'Williams',
    email: 'emily.williams@example.com',
    phone: '+1567890123',
    documentType: 'Passport',
    documentNumber: 'CD901234',
  },
  {
    id: uuidv4(),
    firstName: 'David',
    lastName: 'Brown',
    email: 'david.brown@example.com',
    phone: '+1654321098',
    documentType: 'ID Card',
    documentNumber: 'ZW567890',
  },
  {
    id: uuidv4(),
    firstName: 'Sarah',
    lastName: 'Miller',
    email: 'sarah.miller@example.com',
    phone: '+1098765432',
    documentType: 'Passport',
    documentNumber: 'EF123456',
  },
  {
    id: uuidv4(),
    firstName: 'Robert',
    lastName: 'Wilson',
    email: 'robert.wilson@example.com',
    phone: '+1234509876',
    documentType: 'Driver License',
    documentNumber: 'DL678901',
  },
  {
    id: uuidv4(),
    firstName: 'Jennifer',
    lastName: 'Taylor',
    email: 'jennifer.taylor@example.com',
    phone: '+1876543210',
    documentType: 'ID Card',
    documentNumber: 'UV234567',
  },
  {
    id: uuidv4(),
    firstName: 'William',
    lastName: 'Anderson',
    email: 'william.anderson@example.com',
    phone: '+1345678901',
    documentType: 'Passport',
    documentNumber: 'GH890123',
  },
  {
    id: uuidv4(),
    firstName: 'Elizabeth',
    lastName: 'Thomas',
    email: 'elizabeth.thomas@example.com',
    phone: '+1789012345',
    documentType: 'Driver License',
    documentNumber: 'DL456789',
  },
]; 